# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UICreator-CreatingAndCombiningViews' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod "UIContainer", :path => "~/umobi/UIContainer"
  pod "UICreator", :path => "~/umobi/UICreator"
  # Pods for CreatingAndCombiningViews

end
