use_frameworks!

target 'UICreator-Examples_Example' do
  pod 'UICreator-Examples', :path => '../'

  pod "SnapKit"
  pod "UIContainer", '~> 1.2.0-beta.3'
  pod "UICreator", '~> 1.0.0-alpha.5'

  target 'UICreator-Examples_Tests' do
    inherit! :search_paths

    
  end
end
