use_frameworks!

target 'UICreator-Examples_Example' do
  pod 'UICreator-Examples', :path => '../'

  pod "SnapKit"
  pod "UIContainer", :path => "../../../umobi/UIContainer"
  pod "UICreator", :path => "../../../umobi/UICreator"

  target 'UICreator-Examples_Tests' do
    inherit! :search_paths

    
  end
end
