# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TVExample1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TVExample1
  pod "SnapKit"
  pod "UIContainer", :path => "~/Documents/umobi/UIContainer"
  pod "UICreator", :path => "~/Documents/umobi/UICreator"

end
