# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UICreator-Tests' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UICreator-Tests

  pod "UIContainer", :path => "~/Documents/umobi/UIContainer"
  pod "UICreator", :path => "~/Documents/umobi/UICreator"
  pod "EasyAnchor", :git => "https://github.com/brennobemoura/EasyAnchor"

end
